---
- name: Update package (Debian/Ubuntu)
  apt:
    update_cache: yes
    upgrade: dist
  when: "'Debian' in ansible_distribution or 'Ubuntu' in ansible_distribution"

- name: Update package  (RedHat/CentOS)
  yum:
    name: '*'
    state: latest
  when: "'RedHat' in ansible_distribution or 'CentOS' in ansible_distribution"

- name: Update package packages (SUSE)
  zypper:
    name: '*'
    state: latest
  when: "'SLES' in ansible_distribution or 'openSUSE' in ansible_distribution"
